stages:
  - deploy

image: alpine
before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy :
  stage: deploy
  only:
    - main
  script:
    - ssh -o StrictHostKeyChecking=no tegar@prod.srv.maugini.in -p 4563 "ls; cd skripsi_pelaporan;git pull origin main;git checkout main ; composer install;composer dump-autoload; php artisan migrate --seed; php artisan config:clear;"
    - echo "DONE"


